version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Build package
          command: npm run build

      - run:
          name: Run Jest and Collect Coverage Reports
          command: npm run test

      - run:
          name: Test package size
          command: npm run bundle-size

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm run release
      - gh-pages/deploy:
          build-dir: example/build
          requires:
            - example/build
          ssh-fingerprints: 'ff:22:gs:v6:gg:2g:22:7j:73:gf:ja:36:ff:y2:22:89'
workflows:
  version: 2
  prepare-pr:
    jobs:
      - test
  deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
                - /rc-.*/
      - deploy:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
                - /rc-.*/
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
