name: Main CI

on:
  workflow_dispatch:
    inputs:
        distTag:
          description: 'Dist tag to publish'
          required: true
          default: 'latest'
  pull_request:
  push:
    branches:
      - '*'

jobs:
  build_and_testing:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2-beta
        with:
          always-auth: true
          node-version: 12
      - name: Creates local .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - uses: actions/cache@v2
        name: Cache node modules
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: |
          npm install

      - name: Build & Testing
        run: |
          npm run lint
          npm run build
          npm run test
          npm run bundle-size

      - name: Release
        if: ${{github.event.inputs.distTag == 'latest' || github.event.inputs.distTag == 'next'}}
        run: |
          git config --global user.email "sergiomorenoalbert@gmail.com"
          git config --global user.name "CI"
          npm run release